name: OpenWebUI Auto-Sync

on:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne
  repository_dispatch: # Déclenchement manuel via API
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configurer upstream
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git
          git fetch upstream

      - name: Fusionner les changements (résolution des conflits)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git merge upstream/main --no-commit --no-ff --allow-unrelated-histories || true

          git checkout --ours frontend/static/favicon.png
          git checkout --ours frontend/static/opensearch.xml
          git checkout --ours src/lib/constants.ts
          git checkout --ours backend/open_webui/static/favicon.ico
          git checkout --ours backend/open_webui/static/favicon.png
          git checkout --ours static/static/*
          git checkout --ours src/lib/components/layout/Sidebar/UserMenu.svelte
          git checkout --ours config.js
          git checkout --ours generate-config.sh
          git checkout --ours Dockerfile
          git checkout --ours src/app.html
          git checkout --ours update_ollama_models.sh
      
          git add .

          git commit -m "Merge upstream + préservation des fichiers personnalisés"

          git push origin main


