name: OpenWebUI Auto-Sync

on:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne
  repository_dispatch: # Déclenchement manuel via API
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configurer upstream
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git
          git fetch upstream

      - name: Fusionner les changements
        run: |
          git merge upstream/main --no-commit --no-ff --allow-unrelated-histories
          # Conserver les fichiers personnalisés
          git checkout HEAD -- frontend/static/favicon.png
          git checkout HEAD -- frontend/static/opensearch.xml
          git checkout HEAD -- src/lib/constants.ts
          git checkout HEAD -- backend/open_webui/static/favicon.ico
          git checkout HEAD -- backend/open_webui/static/favicon.png
          git checkout HEAD -- static/static/*
          git checkout HEAD -- src/lib/components/layout/Sidebar/UserMenu.svelte
          git checkout HEAD -- config.js
          git checkout HEAD -- generate-config.sh
          git checkout HEAD -- Dockerfile
          git checkout HEAD -- src/app.html
          git checkout HEAD -- .github/*
          git commit -m "Merge upstream + préservation customisations"
          git push origin main
