name: OpenWebUI Auto-Sync

on:
  schedule:
    - cron: '0 0 * * *' # Exécution quotidienne
  repository_dispatch: # Déclenchement manuel via API

jobs:
  sync-and-update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Configurer upstream
        run: |
          git remote add upstream https://github.com/open-webui/open-webui.git
          git fetch upstream

      - name: Fusionner les changements
        run: |
          git merge upstream/main --no-commit --no-ff
          # Conserver les fichiers personnalisés
          git checkout HEAD -- frontend/static/*
          git checkout HEAD -- src/lib/constants.ts
          git commit -m "Merge upstream + préservation customisations"
          git push origin main
