name: Sync OpenWebUI with Customizations

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Delete contents of 'app' directory
        run: |
          rm -rf app/*
          find app -type f -print0 | while IFS= read -r -d $'\0' file; do
            rm -f "$file"
          done
          find app -type d -empty -print0 | while IFS= read -r -d $'\0' dir; do
            rmdir "$dir"
          done

      - name: Copy 'custom-app' to 'app'
        run: cp -r custom-app/. app/

      - name: Checkout OpenWebUI
        uses: actions/checkout@v4
        with:
          repository: open-webui/open-webui
          ref: main
          path: open-webui
          fetch-depth: 0

      - name: Merge OpenWebUI into 'app' (excluding conflicts)
        run: |
          rsync -av --delete \
            --exclude='static/favicon.png' \
            --exclude='static/opensearch.xml' \
            --exclude='src/lib/constants.ts' \
            --exclude='backend/open_webui/static/favicon.ico' \
            --exclude='backend/open_webui/static/favicon.png' \
            --exclude='static/static/*' \
            --exclude='src/lib/components/layout/Sidebar/UserMenu.svelte' \
            --exclude='config.js' \
            --exclude='generate-config.sh' \
            --exclude='Dockerfile' \
            --exclude='src/app.html' \
            --exclude='update_ollama_models.sh' \
            open-webui/ app/

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"
          git add app/*
          git commit -m "Sync with OpenWebUI and apply custom app" || echo "No changes to commit"
          git push origin main
